import {
  type LucideIcon,
  MessageSquare,
  Database,
  BrainCircuit,
  Settings2,
  ArrowUp,
  Plus,
  Search,
  Activity,
  Pin,
  ScrollText,
  History,
  Zap,
  Loader2,
  CheckCircle2,
  AlertCircle,
  FileCode,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  chat: MessageSquare,
  memory: Database,
  brain: BrainCircuit,
  settings: Settings2,
  send: ArrowUp,
  add: Plus,
  search: Search,
  activity: Activity,
  pin: Pin,
  history: History,
  scroll: ScrollText,
  zap: Zap,
  spinner: Loader2,
  success: CheckCircle2,
  error: AlertCircle,
  artifacts: FileCode,
};
