'use client';

import React, { useState } from 'react';
import { AppLayout } from '@/components/dashboard/app-layout';
import { GraphView, GraphViewNode, GraphViewEdge } from '@/components/GraphView';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { RefreshCcw, Filter, GitBranch } from 'lucide-react';

// Demo Data for the initial view
const INITIAL_NODES: GraphViewNode[] = [
    { id: '1', label: 'Sovereign AI' },
    { id: '2', label: 'vLLM' },
    { id: '3', label: 'Qdrant' },
    { id: '4', label: 'Next.js' },
    { id: '5', label: 'Firebase' },
    { id: '6', label: 'Graph Visualization' },
    { id: '7', label: 'Memory System' },
    { id: '8', label: 'Artifacts' },
];

const INITIAL_EDGES: GraphViewEdge[] = [
    { id: 'e1-2', sourceId: '1', targetId: '2', relation: 'runs on' },
    { id: 'e1-3', sourceId: '1', targetId: '3', relation: 'remembers via' },
    { id: 'e1-4', sourceId: '1', targetId: '4', relation: 'interface' },
    { id: 'e1-5', sourceId: '1', targetId: '5', relation: 'runs on' },
    { id: 'e6-1', sourceId: '6', targetId: '1', relation: 'visualizes' },
    { id: 'e7-3', sourceId: '7', targetId: '3', relation: 'stored in' },
    { id: 'e8-1', sourceId: '8', targetId: '1', relation: 'generated by' },
];

export default function GraphPage() {
    const [nodes, setNodes] = useState<GraphViewNode[]>(INITIAL_NODES);
    const [edges, setEdges] = useState<GraphViewEdge[]>(INITIAL_EDGES);

    return (
        <AppLayout>
            <div className="flex flex-col h-[calc(100vh-4rem)] p-4 space-y-4">
                <div className="flex items-center justify-between">
                    <h2 className="text-3xl font-bold tracking-tight">Knowledge Graph</h2>
                    <div className="flex items-center space-x-2">
                        <Button variant="outline" size="sm">
                            <Filter className="mr-2 h-4 w-4" /> Filter
                        </Button>
                        <Button variant="outline" size="sm" onClick={() => {
                            // Simulate refresh
                            setNodes([...INITIAL_NODES]);
                        }}>
                            <RefreshCcw className="mr-2 h-4 w-4" /> Refresh
                        </Button>
                    </div>
                </div>

                <Card className="flex-1 w-full h-full p-0 overflow-hidden border-border/50 shadow-sm relative">
                    <div className="absolute top-4 right-4 z-10 bg-background/80 p-2 rounded-md border text-xs text-muted-foreground backdrop-blur-sm">
                        Nodes: {nodes.length} • Edges: {edges.length}
                    </div>
                    <GraphView
                        nodes={nodes}
                        edges={edges}
                        className="w-full h-full bg-slate-50/50 dark:bg-slate-900/20"
                        onNodeClick={(node) => alert(`Clicked node: ${node.label}`)}
                    />
                </Card>
            </div>
        </AppLayout>
    );
}
